name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-fsharp:
    name: Test F# Solutions
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Install F# tools
      run: |
        dotnet tool install -g fantomas-tool
        dotnet tool install -g dotnet-fsharplint
        
    - name: Build main project
      run: dotnet build ProjectEuler.fsproj --configuration Release
      
    - name: Run tests
      run: |
        echo "Running Problem6 tests..."
        dotnet test tests/Problem6.Tests/Problem6.Tests.fsproj --configuration Release --verbosity quiet --logger "console;verbosity=quiet" --nologo || true
        echo "Running Problem25 tests..."
        dotnet test tests/Problem25.Tests/Problem25.Tests.fsproj --configuration Release --verbosity quiet --logger "console;verbosity=quiet" --nologo || true
      
    - name: Check formatting
      run: fantomas . --check
      
    - name: Run linter
      run: dotnet fsharplint lint .
  test-python:
    name: Test Python Solutions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Test Python solutions
      run: |
        echo "Testing Python implementations..."
        for py_file in src/Problem*/**/*.py; do
          if [ -f "$py_file" ]; then
            echo "Running $py_file"
            python "$py_file" && echo "$py_file executed successfully" || echo "$py_file had issues"
          fi
        done