name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-fsharp:
    name: Test F# Solutions
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Install F# tools
      run: |
        dotnet tool install -g fantomas-tool
        dotnet tool install -g dotnet-fsharplint
        
    - name: Build main project
      run: dotnet build ProjectEuler.fsproj --configuration Release
      
    - name: Run tests
      run: |
        echo "Running Problem6 tests..."
        dotnet test tests/Problem6.Tests/Problem6.Tests.fsproj --configuration Release --verbosity normal
        echo "Running Problem25 tests..."
        dotnet test tests/Problem25.Tests/Problem25.Tests.fsproj --configuration Release --verbosity normal
      
    - name: Check formatting
      run: fantomas . --check
      
    - name: Run linter
      run: dotnet fsharplint lint .